solution/graph_traversal/11725/main.cpp
graph_traversal/11725 soltuion in cpp
=> [ADD] 11725-cpp solution

solution/backtracking/1189/main.cpp
=> [ADD] 1189-cpp solution

solution/graph_traversal/2667/main.cpp
=> [ADD] 2667-cpp solution

solution/graph_traversal/2606/main.cpp
=> [ADD] 2606-cpp solution

solution/graph_traversal/2178/main.cpp
=> [ADD] 2178-cpp solution

solution/graph_traversal/1325/main.cpp
=> [ADD] 1325-cpp solution

solution/dynamic_programming_1/17626/main.py
17626 python  solution 입니다.
자주 참고하던 repo 였는데 PR 남기게 되어서 기쁘네요! 😀
=> [ADD] 17626 python solution

solution/dynamic_programming_1/9095/main.py
=> [ADD] 9095 python solution

solution/tree/1068/main.cpp
=> [UPD] tree Solution 수정

solution/graph_traversal/5547/main.cpp
=> [ADD] 5547-cpp solution

solution/graph_traversal/7569/main.cpp
=> [ADD] 7569-cpp solution

solution/graph_traversal/7576/main.cpp
=> [ADD] 7576-cpp solution

solution/graph_traversal/16918/main.cpp
=> [ADD] 16918-cpp solution

solution/graph_traversal/14502/main.py
알고리즘 공부하는데 큰 도움되고 있습니다!
정말 감사드립니다!
=> Add BOJ14052 Python Solution

solution/graph_traversal/2636/main.cpp
=> [ADD] 2636-cpp-solution

solution/graph_traversal/14502/main.cpp
=> [ADD] 14502-cpp solution

solution/graph_traversal/16234/main.cpp
=> [ADD] 16234-cpp solution

solution/graph_traversal/1012/main.py
=> [ADD] 1012 python solution

solution/brute_force/14500/main.py
bruteforce 14500번 테트로미노 파이썬 풀이입니다.
=> Solve: bruteforce/14500/main.py

solution/graph_traversal/13549/main.cpp
=> [ADD] 13549-cpp-solution

solution/dynamic_programming_2/1520/main.cpp
=> [ADD] 1520-cpp solution

solution/data_structure2/1927/main.py
=> [ADD] 1927 python solution

solution/data_structure2/1302/main.py
=> [ADD] 1302 python solution

solution/string/11720/main.py
=> [ADD] 11720 python solution

solution/string/11365/main.py
=> [ADD] 11365 python solution

solution/string/1181/main.py
=> [ADD] 1181 python solution

solution/brute_force/9094/main.py
=> [ADD] 9094 python solution

solution/graph_traversal/11724/main.py
=> [ADD] 11724 python solution

solution/greedy/11508/main.py
=> [ADD] 11508 python solution

solution/greedy/1931/main.py
=> [ADD] 1931 python solution

solution/brute_force/1969/main.py
=> [ADD] 1969 python solution

solution/brute_force/7568/main.py
=> [ADD] 7568 python solution

solution/brute_force/1436/main.py
=> [ADD] 1436 python solution

solution/implementation/21918/main.py
=> [ADD] 21918 python solution

solution/greedy/11399/main.py
=> [ADD] 11399 python solution

solution/dynamic_programming_1/11727/main.py
=> [ADD] 11727 python solution

solution/binary_search/2805/main.py
=> [ADD] 2805 python solution

solution/binary_search/1654/main.py
=> [ADD] 1654 python solution

solution/brute_force/2503/main.py
=> [ADD] 2503 python solution

solution/brute_force/18511/main.py
18511 파이썬 솔루션입니다. 완전탐색 + 백트랙킹 개념을 활용하여 풀었습니다.
=> [ADD] 18511 python solution

solution/brute_force/5568/main.py
=> [ADD] 5568 python solution

solution/data_structure/1935/main.py
=> [ADD] 1935 python solution

solution/graph_traversal/7569/main.py
=> [ADD] 7569 python solution

solution/data_structure/18258/main.py
=> [ADD] 18258 python solution

solution/data_structure/2164/main.py
=> [ADD] 2164 python solution

solution/data_structure/10866/main.py
=> [ADD] 10866 python solution

solution/data_structure2/14425/main.py
=> [ADD] 14425 python solution

solution/data_structure2/11279/main.py
=> [ADD] 11279 python solution

solution/data_structure2/11286/main.py
=> [ADD] 11286 python solution

solution/brute_force/2798/main.py
=> [ADD] 2798 python solution

solution/brute_force/1145/main.py
=> [ADD] 1145 python solution

solution/string/1316/main.py
=> [ADD] 1316 python solution

solution/math/1978/main.py
=> [ADD] 1978 python solution

solution/data_structure/3986/main.py
=> [ADD] 3986 python solution

solution/graph_traversal/4963/main.py
=> [ADD] 4963 python solution

solution/math/5618/main.py
=> [ADD] 5618 python solution

solution/data_structure2/10546/main.py
=> [ADD] 10546 python solution

solution/data_structure/10845/main.py
=> [ADD] 10845 python solution

solution/math/11653/main.py
=> [ADD] 11653 python solution

solution/brute_force/13410/main.py
=> [ADD] 13410 python solution

solution/math/21919/main.py
=> [ADD] 21919 python solution

solution/math/21920/main.py
=> [ADD] 21920 python solution

solution/greedy/1817/main.py
=> [ADD] 1817 python solution

solution/data_structure/1966/main.py
=> [ADD] 1966 python solution

solution/binary_search/2512/main.py
=> [ADD] 2512 python solution

solution/implementation/2729/main.py
=> [ADD] 2729 python solution

solution/binary_search/2776/main.py
=> [ADD] 2776 python solution

solution/string/10798/main.py
=> [ADD] 10798 python solution

solution/greedy/16435/main.py
=> [ADD] 16435 python solution

solution/string/20154/main.py
=> [ADD] 20154 python solution

solution/data_structure/1021/main.py
=> [ADD] 1021 python solution

solution/data_structure/2346/main.py
=> [ADD] 2346 python solution

solution/greedy/16208/main.py
=> [ADD] 16208 python solution

solution/string/1032/main.py
=> [ADD] 1032 python solution

solution/string/1152/main.py
=> [ADD] 1152 python solution

solution/string/2204/main.py
=> [ADD] 2204 python solution

solution/string/2744/main.py
=> [ADD] 2744 python solution

solution/brute_force/4096/main.py
=> [ADD] 4096 python solution

solution/binary_search/6236/main.py
=> [ADD] 6236 python solution

solution/binary_search/10816/main.py
=> [ADD] 10816 python solution

solution/string/12871/main.py
=> [ADD] 12871 python solution

solution/greedy/14247/main.py
=> [ADD] 14247 python solution

solution/backtracking/1182/main.py
=> [ADD] 1182 python solution

solution/string/3029/main.py
=> [ADD] 3029 python solution

solution/dynamic_programming_1/9461/main.py
=> [ADD] 9461 python solution

solution/dynamic_programming_1/11722/main.py
=> [ADD] 11722 python solution

solution/dynamic_programming_1/13699/main.py
=> [ADD] 13699 python solution

solution/string/16171/main.cpp
=> [ADD] 16171 cpp solution

solution/data_structure/10799/main.cpp
[쇠막대기](https://www.acmicpc.net/problem/10799) 에 대한 솔루션입니다.
=> [ADD] 10799 cpp solution

solution/dynamic_programming_1/1463/main.cpp
[1로 만들기](https://www.acmicpc.net/problem/1463) 에 대한 솔루션입니다.
재귀적으로 푸는 방법이 있는 문제이지만, 분류가 dynamic_programming으로 되어있어서 DP로 된 솔루션을 올렸습니다.
=> [ADD] 1463 cpp solution

solution/binary_search/19637/main.cpp
[IF문 좀 대신 써줘](https://www.acmicpc.net/problem/19637) 에 대한 솔루션입니다.
=> [ADD] 19637 cpp solution

solution/data_structure/1874/main.cpp
[스택 수열](https://www.acmicpc.net/problem/1874) 에 대한 솔루션입니다.
- Using ```std::ostringstream``` instead of ```std::vector``` buffer on ```answer``` will increase readability. but will construct duplicate string when we call ```std::ostringstream::str()```. If you have any idea or solution to make direct stream from ```std::ostringstream``` to ```std::cout```, let me know.
=> [ADD] 1874 cpp solution

solution/simulation/14499/main.py, solution/simulation/14999/main.py
=> [ADD] 14499 python solution

solution/brute_force/15661/main.py
=> [ADD] 15661 python solution

solution/implementation/21608/main.py
=> [ADD] 21608 python solution

solution/simulation/14891/main.py
=> [ADD] 14891 python solution

solution/simulation/3190/main.py
=> [ADD] 3190 python solution

solution/simulation/16234/main.py
=> [ADD] 16234 python solution

solution/brute_force/14620/main.py
=> [ADD] 14620 python solution

solution/simulation/21610/main.py
=> [ADD] 21610 python solution

solution/minimum_spanning_tree/1922/main.py
=> [ADD] 1922 python solution

solution/disjoint_set/1976/main.py
=> [ADD] 1976 python solution

solution/graph_traversal/2589/main.py
=> [ADD] 2589 python solution

solution/dynamic_programming_2/1520/main.py
=> [ADD] 1520 python solution

solution/disjoint_set/1043/main.cpp
=> [Add] - c++ solution 1043

solution/backtracking/16198/main.py
16198 파이썬 솔루션입니다.
추가로, 혹시 Allow edits 옵션이 지난 글에도 안 되어있어서 오늘 체크해 보았는데, 다시 풀려있는 것을 발견하였습니다.
혹시 민상님께서 해결된(?) pull request에선 해당 옵션이 체크 안 되게 하셨는지 궁금합니다.
=> [ADD] 16198 python solution

solution/backtracking/10974/main.py
=> [ADD] 10974 python solution

solution/backtracking/15658/main.py
=> [ADD] 15658 python solution

solution/backtracking/1405/main.py
1405 파이썬 솔루션입니다.
등호 하나를 더 넣어 한참 헤맸네요.
=> [ADD] 1405 python solution

solution/minimum_spanning_tree/1647/main.py
=> [ADD] 1647 python solution

solution/minimum_spanning_tree/21924/main.py
=> [ADD] 21924 python solution

solution/greedy/14916/main.py
=> [ADD] 14916 python solution

solution/greedy/1758/main.py
=> [ADD] 1758 python solution

solution/greedy/20115/main.py
=> [ADD] 20115 python solution

solution/brute_force/17471/main.py
=> [ADD] 17471 python solution

solution/two_pointer/2018/main.py
=> [ADD] 2018 python solution

solution/two_pointer/1940/main.py
=> [ADD] 1940 python solution

solution/dynamic_programming_1/15486/Main.java
문제의 기준대로 풀었습니다.
돈은 상담이 끝나는 날에 받을 수 있기 때문에 i번째 날에 시작해서 끝나는 날의 수익을 기준으로 dp의 점화식을 세웠습니다.
1. `i`일 전까지 일해서 벌 수 있는 최대 금액 + `i`일에 일해서 벌 수 있는 돈
2. 기존에 설정된 `i+1`일에 일을 해서 벌 수 있는 최대 액수
두개 중 하나가 `i+1`일에 벌 수 있는 최대 액수가 됩니다.
=> [ADD] 15486 java solution

solution/two_pointer/2559/main.py
=> [ADD] 2559 python solution

solution/disjoint_set/17352/main.cpp
안녕하세요?
Disjoint Set(분리집합)  17352번 문제
C++ 풀이 추가해봤습니다ㅎ.ㅎ
감사합니다.
=> [ADD] 17352 cpp solution

solution/data_structure/22942/main.cpp
[데이터 체커](https://www.acmicpc.net/problem/22942) 에 대한 풀이입니다.
=> [ADD] 22942 cpp solution

solution/brute_force/2615/Main.java
오목은 8방향 어디든 5개의 바둑알이 놓아져서 만들어집니다.
1. 완성되어 있는 바둑판을 왼쪽 위부터 하나씩 탐색해가며 바둑알이 놓인 점을 찾습니다.
2. 기존 8방 탐색중 4방(오른쪽 위↗, 오른쪽→, 오른쪽 아래↘, 아래↓) 을 우선 탐색해서 5개가 만들어지는지 체크합니다.
3. 오목이 완성된다면 도착한 지점부터 다시 되돌아가며(왼쪽 아래↙, 왼쪽←, 왼쪽 위↖, 위↑) 마찬가지로 5개만 연결되어있는지 체크합니다. **이 이유는 6목 이상의 가능성을 없애기 위함입니다.**
4. 1번 과정과 2번 과정 모두 통과했을 경우 오목이 완성됨이 입증됩니다.
5. 문제에서 항상 가장 왼쪽의 위치, 세로일 경우 가장 위의 위치를 반환하라 했기 때문에 2번 과정에서 타고 돌아갔던 마지막 점을 반환하면 답이 출력됩니다.
=> [ADD] 2615 java solution

solution/greedy/20300/main.cpp
20300 서강근육맨 cpp풀이입니다.
주어진 원소들을 정렬한 후 그리디하게 최대/최소 원소를 매칭시켜 가면서 그 합 중 최솟값을 찾았습니다.
브랜치 정리가 필요하다는 감사한 지적을 해 주신 분이 계셔서 브랜치를 정리하고 다시 PR합니다.
=> [ADD] 20300 cpp solution

solution/greedy/20365/main.cpp
20365 블로그 2 cpp 풀이입니다.
먼저 하나의 색으로 모두 칠한 후 다른 색으로 칠해야 할 문제들 중 연속하지 않은 색 배열들만 찾아서 순서대로 칠해 주면 된다는 것에 착안하여 풀었습니다. 먼저 파랑색 혹은 빨간색이 연속된 부분이 각각 몇 개씩인지 센 후에 둘 중 작은 걸 택하고, 그전에 '처음에 한꺼번에 칠해줘야 할 한 번' 의 횟수를 더해 주는 방식입니다.
브랜치 정리가 필요하다는 감사한 지적을 해 주신 분이 계셔서 브랜치를 정리하고 다시 PR합니다.
=> [ADD] 20365 cpp solution

solution/data_structure/5430/main.py
자료구조 5430 AC python 솔루션입니다. 포인터 2개 잡고 지우는 위치 포인터를 옮겨가면서 풀었습니다.
=> [ADD] 5430 python solution

solution/implementation/14719/main.py
=> [ADD] 14719 python solution

solution/dynamic_programming_1/9655/main.py
미리 사이즈를 지정한 뒤 dp를 채우고 dp[n]으로 답을 구하는 동적계획법을 사용하여 간단하게 풀었습니다.
=> [ADD] 9655 python solution

solution/dynamic_programming_2/17485/main.py
왼쪽 위 대각선에서 오는 경우 :  2
오른쪽 위 대각선에서 오는 경우: 1
위에서 오는 경우 : 0
3개의 상태를 고려하여 dp를 3 x n x m 사이즈로 잡고 동적계획법을 사용하였습니다.
=> [ADD] 17485 python solution

solution/shortest_path/10282/main.py
First, 입력받은 값을 토대로 그래프를 만듭니다.
(코드에서는 dependency)
Second, c의 값을 start로 다익스트라 알고리즘을 사용하여 start로부터 모든 정점의 최소비용(시간)을 구합니다.
(코드에서는 result)
Finally, result 배열에서 갱신된 값들만 counting하고 가장 큰 값을 구합니다.
=> [ADD] 10282 python solution

solution/graph_traversal/1726/main.py
1726 solution
1. 현재 위치의 좌표와 direction을 구합니다.
2. direction방향으로 1~3 순차적으로 갈 수 있는지 체크합니다. 만약 못간다면 continue가 아닌 break를 걸어줍니다. 이 부분이 중요한데 예를 들어, ny = y + dy * 2 일 때 continue가 되지만  ny = y + dy * 3 일 때는 조건문을 통과할 수 있으므로 continue가 아닌 break로 execute flow을 제어합니다.
3. 그 다음 direction에 대해 조사합니다. 이때 서로 반대방향이면 cnt+2, 아닐 경우 cnt+1을 함으로써 q에 넣어줍니다.
4. 현재 좌표 및 dir가 end와 동일하다면 바로 break를 해줍니다(이때가 최소비용).
=> [ADD] 1726 python solution

solution/graph_traversal/16954/main.py
- solution
1. 제자리, 좌우상하, 대각선 총 9개의 dy,dx 를 지정합니다.
2. 움직일수 있는 공간은 현재가 벽이 아니거나 다음에 내려올 벽이 아닌 곳만 방문이 가능합니다.
3. 이때 방문처리는 8 x 8 x time(9) 3차원 배열로 선언합니다.
4. 세로길이가 8이므로 time의 최대길이를 9로 잡았습니다.
5. 위 조건들을 고려하여 bfs를 수행합니다. 만약 (0,7) 좌표를 방문 가능하다면 1를 반환합니다.
=> [ADD] 16954 python solution

solution/shortest_path/1719/main.py
- solution
1. 문제에서 입력받은 값을 토대로 graph(소스에서는 dic)을 만듭니다.
2. 일정 지점으로부터 모든 정점으로의 최소거리를 구할 수 있도록 다익스트라 함수를 구현합니다.
3. 이때 최소비용만을 구하는게 아닌 path도 구해야 하므로 index_result도 생성합니다.
4. 최소비용일때 최소비용 배열만 갱신하는게 아닌 path도 갱신하여 index_result에 저장합니다.
5. 최종 answer를 구현할 때 위에서 구한 path에서 첫번째 정점들만을 출력합니다.
=> [ADD] 1719 python solution

solution/shortest_path/main.py
최단거리 1238 파티 솔루션입니다. 힙 가져와서 다익스트라 이용해서 풀었고, 기존 방향 + 역방향 그래프 2개에 각각 다익스트라를 적용했습니다.
=> [ADD] 1238 python solution

solution/binary_search/1477/main.py
- solution
거리를 mid값으로 두고 이진탐색을 진행합니다. 이때 효율적으로 cnt 값을갱신하기 위해 '//' 연산을 진행하였는데 완전 나누어 떨어질 경우를 고려하여 -1를 해주고 나눠줍니다(만약 나누어 떨어진다면 해당 휴게소 위치랑 겹치기 때문입니다). 그리고 cnt값이 m보다 같거나 작을 경우 answer값을 갱신시켜줍니다. 이는 최대거리를 mid라고 생각한다면 cnt가 m보다 작을 경우 임의로 아무 곳이나 휴게소를 지어도 되기 때문입니다.
=> [Add] 1477 python solution

solution/dynamic_programming_2/21923/main.py
- solution
1. up 함수 구현
(m-1, 0) 에서부터 탐색하며 최댓값으로 dp에 저장합니다(이때 dp[0]에 저장)
2. down 함수 구현
(m-1, n-1) 에서부터 탐색하며 최댓값으로 dp에 저장합니다(이때 dp[1]에 저장)
3. dp[0]와 dp[1]의 각 좌표들을 더한 값 중에 가장 큰 값을 출력합니다.
=> [Add] 21923 python solution

solution/implementation/15806/main.py
- solution
1. 단순 bfs로만 구현하면 시간초과가 납니다. 시간을 줄일 수 있는 방법을 구사해야 됩니다.
2. 곰팡이가 증식할 때 중복해서 증식되는 구간이 있습니다. 예를 들어서 1초에 증식됐던 곳이 3초에 또 증식되어야 할 공간일 수 있습니다.
1 0 0
0 0 0
0 0 0
위처럼 (1,1)에 곰팡이가 있고 1초뒤에는
0 0 0
0 0 1
0 1 0
이 됩니다. 그 다음 1초 뒤에는
1 0 1
0 0 0
1 0 0
이 됩니다. 이때 (1,1)이 또 증식됨을 알 수 있습니다.
따라서 visit배열을 3차원으로 하여 첫번째 차원은 시간으로 정의합니다.
그리고 t%2일때마다 중복될 수 있다는 점을 감안하여 visit[t%2][y][x]가 true라면 중복방문을 피하는 방법을 사용하여 시간초과를 해결합니다.
=> [Add] 15806 python solution

solution/binary_search/3079/main.py
- solution
이분탐색 알고리즘을 이용한 풀이로 키값(mid)를 구하고자 하는 최소시간이라고 생각합니다.
그리고 min값을 0, max값을 조건에서 주어진 최대시간 * m으로 하여 이분탐색을 진행합니다.(max는 한곳에만 모든 인원이 최대시간으로 들어간다고 생각하면 편하다)
그리고 mid를 시간으로 나눠서 몫을 counting하며 m보다 같거나 크다면 충분히 시간을 가졌다는 뜻으로 max를 갱신하고, 아니라면 min을 갱신합니다.
=> [Add] 3079 python solution

solution/data_structure/2504/main.cpp
[괄호의 값](https://www.acmicpc.net/problem/2504) 에 대한 솔루션입니다.
input string을 하나씩 읽어가며,
- '(', '['이 등장할시, 0의 값을 넣어주고 (stack_push),
- ')', ']'이 등장할시, 지금까지의 연산결과(stack_top)를 부모의 연산결과(stack_pop)에 반영
하는 방식으로 짰습니다.
=> [ADD] 2504 cpp solution

solution/implementation/15787/main.py
배열을 이용하여 시도했으나 시간초과 발생
따라서 빠른 연산이 가능한 비트연산을 이용해서 풀어야함.
이때 주의할 점으로 커맨드 3을 할 때 단순히 `train << 1` 을 하면 20번째 비트까지 1이 되는 경우가 존재하므로 이를 0으로 만들어주는 연산을 해야함(필자는 (1<<20) -1를 이용하여 20번째는 0으로 19~0번째는 1로 만들어서 &연산을 진행함)
=> [Add] 15787 python solution

solution/brute_force/21315/main.py
카드를 재조합하는 recursion함수와 1부터 9까지 두개씩 있는 리스트를 순열을 이용해서 순서쌍을 만듭니다.
그 후 모든 순서쌍에 대해서 조사를 합니다.
문제에서 유일성이 보장되었다고 언급하였으므로 중복되는 것은 없다고 판단하고 코드를 짰습니다.
=> [Add] 21315 python solution

solution/dynamic_programming_1/22869/main.py
- solution
dp를 선언하고 돌을 탐색합니다. 이때 건너갈 수 있으면 갱신을 하고 그렇지 않은 경우(k보다 클 경우) 해당 돌에 도착을 못했으므로 다음으로 넘어갑니다. 그 후 최종 마지막번째 돌에 값이 k보다 크면 NO, 같거나 작다면 YES를 출력합니다.
=> [Add] 22869 python solution

solution/graph_traversal/4179/main.py
- solution
일단 주어진 이차원 배열의 가장자리를 고려해 r+2 x c+2 크기의 배열로 board를 만듭니다. 그리고 매분마다 지훈이와 불이 움직이므로 현재 큐, 다음 큐 두 개를 만들어 bfs를 돌립니다. bfs에서는 현재 큐를 토대로 search하고 다음에 갈 수 있는 칸을 next_q에 담아 반환합니다. solution함수에서는 지훈이가 가장자리에 있을 때와 그렇지 않을 때 next_q의 상태를 보고 루프문을 빠져나갈지 결정합니다.
=> [Add] 4179 python solution

solution/binary_search/2470/2470 - 두 용액.py, solution/binary_search/2470/main.py
이분탐색 2470 두 용액 솔루션입니다. bisect 가져와서 풀었습니다. 양수, 음수 담긴 리스트 나누고 이분탐색 사용했습니다.
=> [ADD] 2470 python solution

solution/prefix_sum/11659/main.py
누적 합 11659번 - 구간 합 구하기 4 솔루션입니다.
=> [ADD] python solution 11659

solution/prefix_sum/2015/main.py
누적 합 2015번 수들의 합 4 python 솔루션입니다. defaultdict 사용했습니다
=> [ADD] python solution 2015

solution/backtracking/22944/main.py
- 솔루션
백트래킹을 사용하여 모든 경우를 탐색하고 최솟값을 구하는 방식으로 했습니다.
- 시간초과 발생하는 경우
처음에 2차원 배열로 board를 생성하고 start 지점부터 [0,-1], [0,1], [-1,0], [1,0] 으로 상하좌우 움직이며 탐색하는 방식으로 구현했더니 1%도 못채우고 바로 시간초과 발생했습니다. 이를 해결하기 위해서 조금 더 효율적인 방법으로 구현해야 됐습니다.
- 도착지점과 우산이 있는 지점만 탐색하자
현재 지점이 y, x라면 도착지점 end = [ey,ex] 와 절댓값을 계산[abs(y-ey)+abs(x-ex)]하여 갈 수 있다면 answer과 비교하여 바로 리턴해줍니다. 그렇지 못할 경우 현재 체력과 가지고 있는 우산의 내구성으로 갈 수 있는 우산 지점으로 이동합니다. 이렇게 우산이 있는 지점과 도착 지점만을 고려하여 재귀적으로 호출하기 때문에 효율적으로 처리할 수 있고 시간초과 발생을 피할 수 있습니다.
=> [Add] 22944 python solution

solution/greedy/2141/main.py
그리디 2141번 우체국 python 솔루션입니다. 마을 위치대로 우선 정렬하고, 매 위치마다 오른쪽에 있는 사람 수는 빼고, 왼쪽에 있는 사람 수는 더하면서 거리가 최소가 되는 지점을 정답으로 합니다.
그리디 2285 우체국도 같은 코드로 풀립니다.
=> [Add] 2141 python solution

solution/tree/15681/main.py
트리 15681번 트리와 쿼리 python 솔루션입니다. Root로부터 DFS를 수행하고, leaf에서는 1을 저장하고 return, 나머지는 각 child를 root로 하는 subtree의 node 합 + 1을 저장하고 return합니다.
재귀 한도 설정을 생활화 합시다...
=> [ADD] 15681 python solution

solution/greedy/2812/main.py
그리디 2812 크게 만들기 python 솔루션입니다. 스택에 수 쌓아가면서 지울 수 있을 때 pop 통해 빼냅니다. 여러 위치의 숫자를 지울 수 있을 때 자리수가 큰 쪽을 먼저 지우는 것이 이득입니다.
=> [ADD] 2812 python solution

solution/greedy/2212/main.py
그리디 2212 센서 python 솔루션입니다. 중복되는 센서를 제외하고, 센서 간 거리를 구한 뒤 정렬 후, 가장 큰 k개 거리를 제외한 것이 정답입니다.
=> [ADD] 2212 python solution

solution/graph_traversal/1707/main.py
그래프 탐색 1707 이분 그래프 python 솔루션입니다. 함수 이름을 잘못 적었는데..... DFS를 이용해서 풀었고, neighbor node를 이미 방문한 경우 현재 node와 neighbor node의 label이 같다면 bipartite graph가 아니기 때문에 NO를 출력하도록 했습니다. 또한 모든 node들이 하나의 connected graph 상에 있지 않는 경우도 있어 모든 connected graph에서 한 번씩 DFS가 돌아가도록 했습니다.
=> [ADD] 1707 python solution

solution/math/5618/Main.java
2개 또는 3개의 수의 공약수를 구하는 문제입니다.
1부터 1씩 증가시키면서 주어진 수에 공약수이면 출력되게 했습니다.
=> [ADD] 5618 java solution

solution/math/22864/Main.java
피로도를 고려하여 할 수 있는 일의 최대값을 구하는 문제입니다.
피로도를 보고 일을 할 수 있으면 진행, 할 수 없는 상태이면 휴식을 하는 방식으로 24시간동안 일을 하도록 시뮬레이션 형식으로 만들었습니다.
=> [ADD] 22864 java solution

solution/math/2745/Main.java
진법 변환 문제입니다.
각 자리수를 char로 받아서 10진법으로 바꾸어 계산하였습니다.
=> [ADD] 2745 java solution

solution/greedy/2217/Main.java
가장 많이 들 수 있는 무게를 구하는 문제입니다.
들 수 있는 무게를 입력받고 오름차순으로 정렬한 후
무게는 늘리고 줄 개수는 줄여가며 최대값을 찾아 출력합니다.
=> [ADD] 2217 java solution

solution/greedy/1541/Main.java
주어지는 식에 괄호를 쳐서 최소값을 구하는 문제입니다.
입력을 기호를 포함하여 토큰화 한 뒤
첫번째 마이너스를 만나기 전까지 모든 수를 더하고 그 이후의 수는 모두 빼면 최소값이 됩니다.
=> [ADD] 1541 java solution

solution/string/20437/Main.java
정확히 어떤 문자를 K개 포함하는 가장긴, 짧은 문자열을 구하는 문제입니다.
입력값을 읽어서 각 알파벳별로 몇번나왔는지 기록하고 K랑 같거나 많이 나온 알파벳에 한하여 검사합니다.
정확히 K개가 되면 시작과 끝을 min, max값과 비교하여 기록합니다.
=> [ADD] 20437 java solution

solution/dynamic_programming_1/1912/Main.java
수를 몇개 선택하여 최대값을 만드는 문제입니다.
dp[i] 에 arr[0~i]까지의 합 중 최대값을 저장하여 dp의 최대값을 출력합니다.
dp[i] = Math.max(dp[i - 1] + arr[i], arr[i]);
=> [ADD] 1912 java solution

solution/dynamic_programming_1/1106/Main.java
최소인원을 채우기 위한 홍보에 필요한 최소 투자비용을 구하는 문제입니다.
dp[i]에 i원으로 몇명의 고객을 늘릴 수 있는지 저장하였고
i원일 때 그 돈으로 홍보할 수 있는 최대의 인원을 각 도시를 돌며 확인하여 갱신합니다.
=> [ADD] 1106 java solution

solution/dynamic_programming_1/1010/Main.java
다리를 놓는 문제인데 조합문제로 바꿀 수 있습니다.
0 C 0 부터 29 C 29 까지 DP로 값을 저장해놓고 입력받은 수에 맞추어 출력합니다.
=> [ADD] 1010 java solution

solution/dynamic_programming_1/9655/Main.java
창영, 상근의 승자를 출력하는 문제인데
N이 짝수일 때는 반드시 창영이가, 홀수일 때는 상근이가 이기게 됩니다.
=> [ADD] 9655 java solution

solution/dynamic_programming_1/11726/Main.java
타일을 채우는 방법의 수를 구하는 문제입니다.
점화식은 dp[i] = dp[i - 1] + dp[i - 2] 이며 10007로 나눈 나머지를 저장합니다.
=> [ADD] 11726 java solution

solution/dynamic_programming_1/2407/Main.java
매우 큰수가 나오는 조합 구하기 입니다.
DP를 이용하되 long 범위를 벗어나기에 BigInteger을 사용하여 구했습니다.
=> [ADD] 2407 java solution

solution/data_structure/5430/Main.java
시간이 빡빡해서 실제로 뒤집기, 삭제하기를 구현하지 않고 편법을 이용했습니다.
뒤집기는 실제로 뒤집는 것이 아닌 앞에서 뒤로 읽는걸 뒤에서 앞으로 읽게 하였고,
삭제하기는 실제 삭제가 아닌 front포인터를 하나 증가시키는 식으로 구현했습니다.
출력도 빠른 출력을 이용하여 출력했습니다.
=> [ADD] 5430 java solution

solution/tree/15681/Main.java
서브트리의 정점의 수를 구하는 문제입니다.
문제에 주어진 힌트를 똑같이 구현하였습니다.
=> [ADD] 15681 java solution

solution/graph_traversal/14940/Main.java
도착지점으로부터 얼만큼 떨어져있는지 출력하는 문제입니다.
입력받을 때 도착지점을 저장해놓고 도착지점을 기준으로 bfs를 진행하여 각각 거리를 계산합니다.
=> [ADD] 14940 java solution

solution/graph_traversal/17836/Main.java
검을 이용하여 공주를 구하거나, 그냥 구하거나, 못구하거나 문제입니다.
입력받을 때 검 위치를 저장해 놓고 시작점을 기준으로 bfs를 실행합니다.
검을 사용했을 때, 사용하지 않았을 때 를 비교하여 작은 값을 구하고 T와 비교하여 fail인지 아닌지 판단합니다.
=> [ADD] 17836 java solution

solution/graph_traversal/16954/Main.java
벽이 매 시간마다 한칸씩 내려오는데 탈출 가능한지 아닌지 구하는 문제입니다.
bfs + 시뮬레이션 으로 풀었고 입력받을 때 벽 개수를 구해서 벽이 다 없어지거나 도착지에 도달하면 1을 출력합니다. 현 위치에서 이동할 수 있는 곳을 큐에 넣고 다음번 while문에서 큐에 있었던 모든 값을 사용하고 벽을 움직여야 합니다.
=> [ADD] 16954 java solution

solution/graph_traversal/16954/main.cpp
시뮬레이션 + bfs를 혼합하여 풀었습니다.
자바풀이와 동일합니다.
=> [ADD] 16954 cpp solution

solution/graph_traversal/17836/main.cpp
bfs로 거리를 구해놓고
검을 사용하였을때 사용하지 않았을 때로 구분하여 풀이하였습니다.
자바와 동일합니다.
=> [ADD] 17836 cpp solution 

solution/two_pointer/20922/main.cpp
투포인터 문제풀이 입니다.
K개를 포함하지 않을때는 end포인터를 늘려 최대 길이를 늘려주고
K개를 초과하면 begin포인터를 늘려 K개이하로 개수를 떨어뜨리면서 최대값을 구합니다.
자바와 동일합니다.
=> [ADD] 20922 cpp solution

solution/prefix_sum/11659/main.cpp
누적합을 구해놓고 구할 값을 입력받아 출력합니다.
자바와 동일합니다.
=> [ADD] 11659 cpp solution

solution/brute_force/18808/main.py
- solution
1. rotate 함수
전달 받은 좌표값들을 토대로 90도 회전하는 함수
2.  check 함수
전달 받은 스티커가 지금까지의 board판에 붙일 수 있는지 검사
3.  main
- 스티커들을 입력받을 때 해당 스티커의 최대길이와 좌표들을 저장한다.
- 스티커들을 q에 넣고 차례대로 board판에 붙일 수 있는지 check한다. 이때 총 회전 4번을 돌려도 board판에 붙일 수 없다면 continue한다.
- 큐에 들어있는 모든 스티커들이 사라지면 board판에 존재하는 스티커 좌표들을 카운팅한다(필자의 경우 visit으로 좌표들을 저장했기 때문에 visit의 길이를 반환했다.
=> [Add] 18808 python solution

solution/brute_force/13140/main.cpp
고유 문자에 대해 임의의 숫자를 배분해 답을 찾는 brute force 방식으로 풀었습니다.
고유 문자의 개수 : "helowrd" -> 7개
배분해야하는 수 : 0 ~ 9 -> 10개
10가지 숫자들에서 고유 문자 7개로 임의의 배분을 해야하므로 순열입니다. 
10P7로 next_permutation을 사용했으며 숫자를 배정 후 정답이면 출력했습니다.
=> Add cpp solution 13140

solution/dynamic_programming_2/18427/main.py
- solution
N수 만들기처럼 
현재 사용하는 블록 + 이전에 구했던 블록들의 합 = 현재 쌓아야 될 높이
방식으로 구현하였습니다.
즉, dp를 높이를 기준으로 값을 쌓아가며 H와 같거나 보다 작은 모든 경우를 탐색합니다.
=> [Add] 18427 python solution

solution/dynamic_programming_2/14567/main.py
위상정렬 + 다이나믹 프로그래밍
위상정렬 알고리즘을 이용하여 `indegree`를 통해 들어오는 간선이 없으면 큐에 넣어주고 이때 `dp`에 min값으로 갱신해준다.
=> [Add] 14567 python solution

solution/greedy/13164/main.py
그리디 13164번 행복 유치원 python 솔루션입니다. 원생들 간 키 차이를 정렬하고, 작은 것부터 n-k개 greedy하게 더했습니다.
=> [ADD] python solution 13164

solution/brute_force/21278/main.py
사용한 알고리즘
- BFS
- Combination
임의의 지점을 두 개 고르고, 각 지점으로부터 움직일 때마다 +1를 하여 최단거리를 구합니다(이를 위해 BFS 알고리즘을 사용).
임의의 지점 두 개를 고를 때 다음과 같은 규칙을 세웁니다.
- 첫 번째 지점의 인덱스는 두 번째 지점의 인덱스보다 항상 작아야 한다.
- 순서쌍을 고려안하고 중복없이 추출해야 한다. 즉, (1, 2)와 (2, 1)을 같은 걸로 취급한다.
이를 위해 combination 알고리즘을 사용하여 임의의 두 점을 지정한다.
주어진 점 N개에 대하여 두 개의 지점씩 모두 골라서 거리를 계산하고 조건에 맞게 최단거리 및 세울 가게들의 지점을 담아 return 하여 출력합니다.
=> [ADD] 21278 python solution

solution/data_structure2/21942/main.py
- 사용한 알고리즘
문자열(str -> 분 단위 시간)
자료구조 dictionary(hashmap)
- 솔루션
작성된 정보가 담긴 `info`에서 읽어온 `data`를 문자열 파싱하고 자료구조 dictionary에 넣습니다. 이때 문제조건에서 한 사람당 같은 종류의 부품을 두 개 이상 가져올 수 없다 했으니 dictionary에 이미 키(사람 및 아이템)이 있다면 빌려간 적이 있는 것이므로 시간을 계산해서 벌금을 낼지 판단합니다.
- 개인적인 의견
해당 문제는 다이나믹 프로그래밍 2보다 문자열이나 자료구조에 어울리는 문제 같습니다. @tony9402 께서 다시 확인해주시면 감사하겠습니다.
=> [ADD] 21942 python solution

solution/backtracking/2026/main.py
1. 완전탐색을 통하여 조건을 만족하는 친구들이 존재하는지 확인.
2. 단순히 탐색할 경우 시간초과가 발생하므로 가지를 치면서 탐색할 것
- First, 애초에 친구 수가 K보다 작은 사람은 탐색조차 하지 않을 것
- Second, 탐색하면서 쌓아온 친구들과 모두 관계가 성립하는지 조사. 만족하지 않는다면 거를 것
- Third, 방문한 사람은 당연히 거를 것
- Fourth, 만족한 적이 있다면 이후 더이상 작업하지 않을 것
=> [ADD] 2026 python solution

solution/greedy/1092/Main.java
그리디 알고리즘 문제입니다.
1. 박스와 크레인 정보를 입력받아 내림차순으로 정렬합니다.
2. 옮길 수 없는 상황 0번 인덱스끼리 비교하여 박스 무게가 더 무거우면 -1을 출력합니다.
3. 앞에서부터 차례대로 옮길수 있는지 없는지 비교해가며 진행합니다.
3-1(박스를 옮길 수 있을 때). 옮긴 박스를 리스트에서 제거하고 다음 크레인 
을 확인합니다.
3-2(박스를 옮길 수 없을 때). 크레인은 그대로 두고 다음 박스를 옮길 수 있는 
지 살펴봅니다.
4. 각각 크레인과 박스에 대한 인덱스가 증가하다가 끝까지 다 살펴본 경우에는
그 시간에는 가능한 박스를 모두 옮긴 것 이므로 시간인덱스를 증가시키고 다시 3. 으로 돌아갑니다. 
(박스 리스트 값들이 전부 없어질 때까지 3 ,4 를 반복합니다)
=> [ADD] 1092 java solution

solution/greedy/2141/Main.java
그리디 + 누적합 문제입니다.
1. 마을 위치와 인구수를 입력받습니다
1-1. 입력받음과 동시에 각 인구수를 더해 총 인구수를 구합니다.
2. 마을 위치를 기준으로 오름차순으로 정렬합니다.
3. 첫번째 마을부터 인구수를 더해가며 (중간 값) 이상이 될 때를 찾아 우체국을 설치합니다.
중간값  = (총 인구수 + 1) / 2
=> [ADD] 2141 java solution

solution/dynamic_programming_1/9095/Main.java
기본적인 dp문제입니다.
점화식은 dp[i] = dp[i - 1] + dp[i - 2] + dp[i - 3]입니다.
=> [ADD] 9095 java solution

solution/two_pointer/2470/Main.java
투포인터 문제입니다.
1. 입력받은 용액들을 오름차순으로 정렬한다.
2. 배열의 양 끝점에서 시작하여 각 두 값의 합의 절대값을 구한다.
3. 두 값의 합의 절대값이 min값보다 작으면 두 포인터를 인덱스 번호를 저장한다.
4. front가 end보다 같거나 커질떄까지 2, 3을 반복한다
4-1. 만약 두 값의 합이 0보다 작거나 같으면 front증가(숫자가 커짐)
4-2. 합이 0보다 크면 end감소(숫자가 작아짐)
=> [ADD] 2470 java solution

solution/brute_force/1107/Main.java
완전탐색으로 모든 경우의 수를 살펴 보았습니다.
1. 0 ~ 999999까지 숫자 버튼을 눌러 이동할 수 있는 경우
이동하여 도착지점과의 차이 + 이동할 때 누른 숫자횟수를 더한다.
2. 위에서 구한 값들 중 최소값을 구한다
3. +, - 버튼만을 이용하여 도착지점으로 이동할 때 누르는 횟수를 구하여 
위에 최소값과 비교하여 최종 최소값을 구하고 출력한다.
=> [ADD] 1107 java solution

solution/binary_search/9024/Main.java
이분탐색 문제입니다.
1. 입력받은 숫자 배열을 오름차순으로 정렬합니다.
2. 배열의 i인덱스 숫자를 기준으로 i 오른쪽에 있는 수 중에서 
두 합이 k와 가장 근사한 mid값을 찾는데 이분탐색을 진행합니다.
3. 두 수의 합이 가장 작을 때 min값을 갱신하고 후에 min값과 같은 합이 나오면 
cnt를 증가시킵니다.
=> [ADD] 9024 java solution
